#!/bin/sh
#
# Copyright 2014 Google Inc. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be found
# in the LICENSE file or at https://developers.google.com/open-source/licenses/bsd

#
# Plugin that calls pygmentize to highlight R source files.
#
# TODO: how to choose a plugin that would provide a function outline with
# hyperlinks?

readonly THIS_DIR=$(dirname $0)
. $THIS_DIR/../webpipe-lib.sh

checkDeps() {
  local msg="pygmentize not found.  Run 'sudo apt-get install python-pygments'"
  which pygmentize >/dev/null || die $msg
}

main() {
  local input=$1
  local output=$2

  checkDeps

  # fail if pygmentize fails, etc.
  set -o errexit

  mkdir -p $output

  local inputFilename=$(basename $input)
  local origOut=$output/$inputFilename

  cp $input $origOut

  echo $output  # finished writing directory

  local html=${output}.html

  # Generate HTML.  Note that without the 'full' options, there will be no color.
  # Unfortunately that produces
  pygmentize -f html -O full,style=emacs $input >>$html

  # This is bad
  cat >>$html <<EOF
<p>
  <a href="$origOut">Download $inputFilename</a>
</p>
EOF

  echo $html
}

main "$@"
