#!/bin/sh
#
# Copyright 2014 Google Inc. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be found
# in the LICENSE file or at https://developers.google.com/open-source/licenses/bsd


readonly THIS_DIR=$(dirname $0)
. $THIS_DIR/../webpipe-lib.sh

checkDeps() {
  local msg="markdown not found.  Run 'sudo apt-get install markdown'"
  which markdown >/dev/null || die "$msg"
}

main() {
  local input=$1
  local output=$2

  checkDeps

  # TODO: Test size?
  local html=$output.html
  markdown <$input >$html
  echo $html
}

main "$@"

