#!/bin/sh

readonly THIS_DIR=$(dirname $0)
. $THIS_DIR/../webpipe-lib.sh

main() {
  local input=$1
  local output=$2

  mkdir -p $output
  # original JSON file will be referenced.
  cp $input $output/
  cp $THIS_DIR/shell.html 

  local filename=$(basename $input)
  
  cat >$output/index.html <<EOF
<html>
  <head>
    <title>json $output</title>
    <link href="/plugins/json/static/jsontree.css" rel="stylesheet">
    <script src="/plugins/json/static/jsontree.js"></script>
  </head>

  <body>
    <div id="content"></div>
  </body>

  <script type="text/javascript">
    JSONTree.getAndRender("$filename", document.getElementById("content"));
  </script>

</html>
EOF

  echo $output

  local html=$output.html
  cat >$html <<EOF
<a href="$output">navigate json</a>
EOF

  echo $html
}

main "$@"

