#!/bin/sh

readonly THIS_DIR=$(dirname $0)
. $THIS_DIR/../webpipe-lib.sh

checkDeps() {
  local msg="file not found.  Run 'sudo apt-get install file'"
  which file >/dev/null || die "$msg"
}

showFile() {
  local eInput=$1
  file $eInput 
  echo

  # Show file stat.  TODO: show size pretty printed?
  # note: filename is escaped so could be in a different location
  stat $(readlink -f $eInput)
}

showHtml() {
  local eInput="$1"
  echo '<i>(no render plugin, DEFAULT used)</i><p>'
  echo '<pre>'
  showFile $eInput | WP_HtmlEscape
  echo '</pre>'
}

main() {
  local eInput=$1
  local eOutput=$2

  checkDeps

  local html=$eOutput.html
  showHtml $eInput WP_HtmlEscape >$html
  echo $html
}

main "$@"

