#!/bin/sh
#
# Copyright 2014 Google Inc. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be found
# in the LICENSE file or at https://developers.google.com/open-source/licenses/bsd

# 
# This is just so we can call keep the .py extension.

exec $(dirname $0)/render.py "$@"
