#!/bin/sh
#
# Copyright 2014 Google Inc. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be found
# in the LICENSE file or at https://developers.google.com/open-source/licenses/bsd


readonly THIS_DIR=$(dirname $0)
. $THIS_DIR/../webpipe-lib.sh

set -o errexit

main() {
  local input=$1
  local output=$2

  # If the text is too big, show a preview?
  # Show unicode properties, etc.

  local html=$output.html

  echo '<pre>' >$html

  WP_HtmlEscape <$input >>$html

  echo '</pre>' >>$html

  echo $html
}

main "$@"

