#!/bin/sh

set -o nounset

log() {
  echo 1>&2 "$@"
}

install_message() {
  log "dot not found.  Run 'sudo apt-get install graphviz'"
}

main() {
  local input=$1
  local output=$2
  local output_dir=$3

  log "input $input"

  # These must be RELATIVE, so you can use them as URLs too!
  log "output $output"  # 1.html
  log "output_dir $output_dir"  #1/

  # Script is responsible for this!  I think.
  mkdir -p $output_dir

  which dot >/dev/null || install_message
  local out_png="$output_dir/$(basename $input).png" 
  dot -T png -o $out_png $input

  echo $output_dir  # we wrote it

  # TODO: Use jsont here.
  cat >$output <<EOF
<p>
  <i>Dot file</i>
  <a href="$output_dir">$output_dir</a>
  <img src="$out_png">rendered dot image</img>
</p>
EOF

}

main "$@"

