#!/bin/sh

readonly THIS_DIR=$(dirname $0)
. $THIS_DIR/../webpipe-lib.sh

checkDeps() {
  local msg="aha not found.  Run 'sudo apt-get install aha'"
  which aha >/dev/null || die "$msg"
}

main() {
  local input=$1
  local output=$2

  checkDeps

  aha -f $input > $output
}

main "$@"

