#!/bin/sh

readonly THIS_DIR=$(dirname $0)
. $THIS_DIR/../webpipe-lib.sh

checkDeps() {
  local msg="aha not found.  Run 'sudo apt-get install aha'"
  which aha >/dev/null || die "$msg"
}

main() {
  local action=$1
  if test $action != "scroll"; then
    die "Invalid action '$action'"
  fi
  local input=$2
  local output=$3

  checkDeps

  aha -f $input > $output.html
  echo $output.html
}

main "$@"

