#!/bin/sh
#
# Copyright 2014 Google Inc. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be found
# in the LICENSE file or at https://developers.google.com/open-source/licenses/bsd


readonly THIS_DIR=$(dirname $0)
. $THIS_DIR/../webpipe-lib.sh

checkDeps() {
  local msg="aha not found.  Run 'sudo apt-get install aha'"
  which aha >/dev/null || die "$msg"
}

main() {
  local input=$1
  local output=$2

  checkDeps

  aha -f $input > $output.html
  echo $output.html
}

main "$@"

